---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  root_path: "/home/vagrant/kitchen" # move from /tmp
  require_chef_omnibus: 14
  deprecations_as_errors: true

verifier:
  name: inspec
  sudo: true

# See .kitchen.aws.yml for RedHat Testing
platforms:
- name: centos7
  driver_config:
    box: bento/centos-7

suites:
  - name: rhel7
    includes:
      - centos7
    verifier:
      inspec_tests:
        - test/integration/default/rhel7/inspec # cis-rhel7-level1
    run_list:
      - recipe[cis-rhel::default]
      - recipe[augment::vbox]
    attributes:
      ssh-hardening:
        ssh:
          server:
            cipher: 'aes128-ctr,aes192-ctr,aes256-ctr'
